name: nil_app
description: "A modern video-sharing platform with full-length videos, shorts, and social engagement features."
publish_to: 'none'

version: 1.1.0+4

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  flutter_launcher_icons: ^0.14.4
  video_player: ^2.10.0
  chewie: ^1.8.5
  cloud_firestore: ^6.0.3
  share_plus: ^12.0.0
  url_launcher: ^6.3.1
  timeago: ^3.7.1
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  google_sign_in: ^6.2.2
  shared_preferences: ^2.3.5
  http: ^1.2.2
  dio: ^5.7.0
  youtube_player_flutter: ^9.0.3
  cached_network_image: ^3.4.1
  smooth_page_indicator: ^1.2.0+3
  image_picker: ^1.1.2
  cloudinary_public: ^0.23.1
  path: ^1.9.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  uuid: ^4.5.1
  video_thumbnail: ^0.5.3
  connectivity_plus: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter_launcher_icons:
  android: true
  ios: true
  image_path_ios: "assets/nil_app_icon-removebg-preview.png"
  image_path_android: "assets/nil_app_icon-removebg-preview.png"
  adaptive_icon_foreground: "assets/nil_app_icon-removebg-preview.png"
  adaptive_icon_background: "#00000000"   # fully transparent


flutter:
  uses-material-design: true

  assets:
    - assets/nil_app_icon-removebg-preview.png
