// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu3KHFpPKuiOM66yh3Hzbg8_DV-xLH-00',
    appId: '1:245384420905:web:401bb21ac0986ace6e4638',
    messagingSenderId: '245384420905',
    projectId: 'nilstream',
    authDomain: 'nilstream.firebaseapp.com',
    databaseURL: 'https://nilstream-default-rtdb.firebaseio.com',
    storageBucket: 'nilstream.firebasestorage.app',
    measurementId: 'G-W29M84RPHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDppsuabFvFz5Ki70V0Ctu2kq5fE370w1Y',
    appId: '1:245384420905:android:12b0e44b24dc5e526e4638',
    messagingSenderId: '245384420905',
    projectId: 'nilstream',
    databaseURL: 'https://nilstream-default-rtdb.firebaseio.com',
    storageBucket: 'nilstream.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATTLQsn_acF0XHiNHVG24y8Dy7OdtD89E',
    appId: '1:245384420905:ios:9bd0985a883da0156e4638',
    messagingSenderId: '245384420905',
    projectId: 'nilstream',
    databaseURL: 'https://nilstream-default-rtdb.firebaseio.com',
    storageBucket: 'nilstream.firebasestorage.app',
    iosBundleId: 'com.example.nilApp',
  );
}
